version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
     - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  graphana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - 3000:3000
  graphite_exporter:
    image: prom/graphite-exporter
    container_name: graphite_exporter
    ports:
      - 9108:9108
      - 9109:9109
    volumes:
     - ./graphite_mapping.conf:/tmp/graphite_mapping.conf
    command: --graphite.mapping-config=/tmp/graphite_mapping.conf
